### ISSUE TITLE
Steps in "Add a custom domain managed by GoDaddy" Do not work

### ISSUE THREAD

**Issue by notAmine** [awslabs/aws-amplify-console-user-guide#67]
Dear AWS Amplfy team,
After following the steps of the documentation to the letter I still can not access the amplify app on the root domain name.
The steps for the subdomain worked however the apex domain is not working (ie if I type www.example.com it works but example.com does not) 
I'm happy to provide any additional info to help identify the missing piece.
Also here's a new screenshot of the redirect creation window:
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/30655253/214392858-709f90ce-4ab2-428f-b2f9-5a00173e67a6.png">

Thanks! 
Amine

**Comment by KristinaPeterson** [comment]
Hello Amine. Thank you for your feedback. I'm sorry that the documentation isn't helping you with setting up forwarding in GoDaddy. These instructions are still accurate. There might be another issue with your configuration that the Amplify engineering team can investigate. You can search this repo to see if your situation has already been addressed or post a new issue:
https://github.com/aws-amplify/amplify-hosting/issues
